---
# install apache tasks

- name: install apache
  yum: name=httpd state=latest
- name: start apache and enabled
  service: name=httpd state=started enabled=yes
- name: change owner
  file: dest=/var/www/html owner=vagrant recurse=yes
- name: copy http.conf.custom
  copy: src=httpd.conf.custom dest=/etc/httpd/conf/httpd.conf force=yes backup=yes